language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - windows
script:
  - cargo build --release --verbose
  - cargo test --release --verbose
  - cargo clippy --release --verbose
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
